[Resolves] : Update worflown7.yml

diff --git a/.github/workflows/worflown7.yml b/.github/workflows/worflown7.yml
--- a/.github/workflows/worflown7.yml
+++ b/.github/workflows/worflown7.yml
@@ -31,6 +31,20 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v4
 
+    - name: Check commit messages
+      run: |
+        COMMIT_MESSAGES=$(git log --format=%s ${{ github.event.before }}..${{ github.sha }})
+
+        for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
+          if ! [[ $COMMIT_MESSAGE =~ ^\[(Implement|Resolves|Refactor)\] : .{10,45}$ ]]; then
+            echo "Error: Commit message does not follow the required format or length."
+            echo "Allowed formats: [Implement], [Resolves], [Refactor]"
+            echo "Allowed length: between 10 and 45 characters"
+            exit 1
+          fi
+        done
+
+
     - name: Set up JDK 7
       uses: actions/setup-java@v3
       with:
